create table Person (id integer not null auto_increment, birthdate birthdate not null, firstname firstname not null, name name not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname firstname not null, name name not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname firstname not null, name name not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate birthdate not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table HP (id integer not null auto_increment, address varchar(255), login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, hp_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, health_professional_number integer, intern bit, hp_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime(6) not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table HP add constraint UK_rqlmdfivh49fpfnwia5pubspg unique (login);
alter table Manager add constraint FKpvglb315sb047136dgvmnvhov foreign key (hp_id) references HP (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKgg5kqegrq72nohky7kuj9abgm foreign key (hp_id) references HP (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table HP (id integer not null auto_increment, address varchar(255), login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, hp_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, health_professional_number integer, intern bit, hp_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime(6) not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table HP add constraint UK_rqlmdfivh49fpfnwia5pubspg unique (login);
alter table Manager add constraint FKpvglb315sb047136dgvmnvhov foreign key (hp_id) references HP (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKgg5kqegrq72nohky7kuj9abgm foreign key (hp_id) references HP (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table HP (hpid integer not null auto_increment, address varchar(255), login varchar(255) not null, password varchar(255) not null, primary key (hpid)) engine=InnoDB;
create table Manager (mid integer not null auto_increment, hp_hpid integer, person_peid integer, primary key (mid)) engine=InnoDB;
create table Medecin (did integer not null auto_increment, health_professional_number integer, intern bit, hp_hpid integer, person_peid integer, primary key (did)) engine=InnoDB;
create table Person (peid integer not null auto_increment, birthdate datetime(6) not null, firstname varchar(255) not null, name varchar(255) not null, primary key (peid)) engine=InnoDB;
create table Salle (numero integer not null, name varchar(255), primary key (numero)) engine=InnoDB;
alter table HP add constraint UK_rqlmdfivh49fpfnwia5pubspg unique (login);
alter table Manager add constraint FKd4q4of8vmd1ya6obbdcqnnjs0 foreign key (hp_hpid) references HP (hpid);
alter table Manager add constraint FK9agxpsrxep91q0q4eecdxg30b foreign key (person_peid) references Person (peid);
alter table Medecin add constraint FKi11gbsf6x63vufdpkx03kbnra foreign key (hp_hpid) references HP (hpid);
alter table Medecin add constraint FKbbyncu9fh02c3m7qulkf4jauu foreign key (person_peid) references Person (peid);
create table HP (hpid integer not null auto_increment, address varchar(255), login varchar(255) not null, password varchar(255) not null, primary key (hpid)) engine=InnoDB;
create table Manager (mid integer not null auto_increment, hp_hpid integer, person_peid integer, primary key (mid)) engine=InnoDB;
create table Medecin (did integer not null auto_increment, health_professional_number integer, intern bit, hp_hpid integer, person_peid integer, primary key (did)) engine=InnoDB;
create table Person (peid integer not null auto_increment, birthdate datetime(6) not null, firstname varchar(255) not null, name varchar(255) not null, primary key (peid)) engine=InnoDB;
create table Salle (numero integer not null, name varchar(255), primary key (numero)) engine=InnoDB;
alter table HP add constraint UK_rqlmdfivh49fpfnwia5pubspg unique (login);
alter table Manager add constraint FKd4q4of8vmd1ya6obbdcqnnjs0 foreign key (hp_hpid) references HP (hpid);
alter table Manager add constraint FK9agxpsrxep91q0q4eecdxg30b foreign key (person_peid) references Person (peid);
alter table Medecin add constraint FKi11gbsf6x63vufdpkx03kbnra foreign key (hp_hpid) references HP (hpid);
alter table Medecin add constraint FKbbyncu9fh02c3m7qulkf4jauu foreign key (person_peid) references Person (peid);
create table HP (hpid integer not null auto_increment, address varchar(255), login varchar(255) not null, password varchar(255) not null, primary key (hpid)) engine=InnoDB;
create table Manager (mid integer not null auto_increment, hp_hpid integer, person_peid integer, primary key (mid)) engine=InnoDB;
create table Medecin (did integer not null auto_increment, health_professional_number integer, intern bit, hp_hpid integer, person_peid integer, primary key (did)) engine=InnoDB;
create table Person (peid integer not null auto_increment, birthdate datetime(6) not null, firstname varchar(255) not null, name varchar(255) not null, primary key (peid)) engine=InnoDB;
create table Salle (numero integer not null, name varchar(255), primary key (numero)) engine=InnoDB;
alter table HP add constraint UK_rqlmdfivh49fpfnwia5pubspg unique (login);
alter table Manager add constraint FKd4q4of8vmd1ya6obbdcqnnjs0 foreign key (hp_hpid) references HP (hpid);
alter table Manager add constraint FK9agxpsrxep91q0q4eecdxg30b foreign key (person_peid) references Person (peid);
alter table Medecin add constraint FKi11gbsf6x63vufdpkx03kbnra foreign key (hp_hpid) references HP (hpid);
alter table Medecin add constraint FKbbyncu9fh02c3m7qulkf4jauu foreign key (person_peid) references Person (peid);
