create table Person (id integer not null auto_increment, birthdate birthdate not null, firstname firstname not null, name name not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname firstname not null, name name not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname firstname not null, name name not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate birthdate not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
create table Login (id integer not null auto_increment, login varchar(255) not null, password varchar(255) not null, primary key (id)) engine=InnoDB;
create table Manager (id integer not null auto_increment, address varchar(255), login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Medecin (id integer not null auto_increment, address varchar(255), health_professional_number integer, intern bit, login_id integer, person_id integer, primary key (id)) engine=InnoDB;
create table Person (id integer not null auto_increment, birthdate datetime not null, firstname varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table Salle (id integer not null auto_increment, nom varchar(255), numero integer not null, primary key (id)) engine=InnoDB;
alter table Login add constraint UK_6cetnagnihchjb4qvhi3ndvcb unique (login);
alter table Manager add constraint FKlw7nex01it7yhel54xnba7md7 foreign key (login_id) references Login (id);
alter table Manager add constraint FKnbmn78u49t6eikyk9a9qwif8a foreign key (person_id) references Person (id);
alter table Medecin add constraint FKlvc9t4e7fmw9acm9fe2a2254n foreign key (login_id) references Login (id);
alter table Medecin add constraint FK53bjw9f02ihp8mr1yaxsvvw9g foreign key (person_id) references Person (id);
