drop table if exists Person;
drop table if exists Person;
drop table if exists Person;
drop table if exists Person;
drop table if exists Login;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
