drop table if exists Person;
drop table if exists Person;
drop table if exists Person;
drop table if exists Person;
drop table if exists Login;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKlw7nex01it7yhel54xnba7md7;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKlvc9t4e7fmw9acm9fe2a2254n;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists Login;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKpvglb315sb047136dgvmnvhov;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKgg5kqegrq72nohky7kuj9abgm;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists HP;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKpvglb315sb047136dgvmnvhov;
alter table Manager drop foreign key FKnbmn78u49t6eikyk9a9qwif8a;
alter table Medecin drop foreign key FKgg5kqegrq72nohky7kuj9abgm;
alter table Medecin drop foreign key FK53bjw9f02ihp8mr1yaxsvvw9g;
drop table if exists HP;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKd4q4of8vmd1ya6obbdcqnnjs0;
alter table Manager drop foreign key FK9agxpsrxep91q0q4eecdxg30b;
alter table Medecin drop foreign key FKi11gbsf6x63vufdpkx03kbnra;
alter table Medecin drop foreign key FKbbyncu9fh02c3m7qulkf4jauu;
drop table if exists HP;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKd4q4of8vmd1ya6obbdcqnnjs0;
alter table Manager drop foreign key FK9agxpsrxep91q0q4eecdxg30b;
alter table Medecin drop foreign key FKi11gbsf6x63vufdpkx03kbnra;
alter table Medecin drop foreign key FKbbyncu9fh02c3m7qulkf4jauu;
drop table if exists HP;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
alter table Manager drop foreign key FKd4q4of8vmd1ya6obbdcqnnjs0;
alter table Manager drop foreign key FK9agxpsrxep91q0q4eecdxg30b;
alter table Medecin drop foreign key FKi11gbsf6x63vufdpkx03kbnra;
alter table Medecin drop foreign key FKbbyncu9fh02c3m7qulkf4jauu;
drop table if exists HP;
drop table if exists Manager;
drop table if exists Medecin;
drop table if exists Person;
drop table if exists Salle;
